# Generated by Django 5.1.15 on 2026-05-22 06:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0003_alter_document_status'),
        ('parsing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedSummary',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=32)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_current', models.BooleanField(db_index=True, default=True)),
                ('summary_json', models.JSONField(blank=True, default=dict)),
                ('model_metadata', models.JSONField(blank=True, default=dict)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('last_error', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_summaries', to='documents.document')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtractedInsight',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('extraction_type', models.CharField(choices=[('executive_overview', 'Executive Overview'), ('eligibility_criteria', 'Eligibility Criteria'), ('submission_deadlines', 'Submission Deadlines'), ('technical_requirements', 'Technical Requirements'), ('scope_of_work', 'Scope of Work'), ('payment_terms', 'Payment Terms'), ('penalties_and_risks', 'Penalties and Risks'), ('mandatory_documents', 'Mandatory Documents'), ('evaluation_criteria', 'Evaluation Criteria')], db_index=True, max_length=64)),
                ('payload', models.JSONField(default=dict, help_text='{"items": [{"requirement", "page", "section", "source_text", "confidence"}]}')),
                ('confidence_score', models.FloatField(default=0.0)),
                ('model_name', models.CharField(blank=True, max_length=128)),
                ('prompt_version', models.CharField(blank=True, max_length=32)),
                ('token_usage', models.JSONField(blank=True, default=dict)),
                ('chunk_ids', models.JSONField(blank=True, default=list)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_insights', to='documents.document')),
                ('generated_summary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='intelligence.generatedsummary')),
            ],
            options={
                'ordering': ['extraction_type'],
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section_title', models.CharField(max_length=512)),
                ('page_start', models.PositiveIntegerField(default=1)),
                ('page_end', models.PositiveIntegerField(default=1)),
                ('chunk_order', models.PositiveIntegerField(default=0)),
                ('chunk_text', models.TextField()),
                ('char_count', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='documents.document')),
                ('parsed_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='parsing.parseddocument')),
            ],
            options={
                'ordering': ['chunk_order'],
                'indexes': [models.Index(fields=['document', 'chunk_order'], name='intelligenc_documen_1dc9c2_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='generatedsummary',
            index=models.Index(fields=['document', 'is_current'], name='intelligenc_documen_20719d_idx'),
        ),
        migrations.AddIndex(
            model_name='extractedinsight',
            index=models.Index(fields=['document', 'extraction_type'], name='intelligenc_documen_c38f6e_idx'),
        ),
        migrations.AddIndex(
            model_name='extractedinsight',
            index=models.Index(fields=['generated_summary', 'extraction_type'], name='intelligenc_generat_5c13da_idx'),
        ),
    ]
