# Generated by Django 5.1.15 on 2026-06-23 05:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_document_status'),
        ('intelligence', '0002_learnedextractionterm'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('value', models.TextField(blank=True)),
                ('description', models.CharField(blank=True, max_length=256)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='FieldFeedback',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_key', models.CharField(db_index=True, max_length=128)),
                ('extraction_type', models.CharField(choices=[('executive_overview', 'Executive Overview'), ('eligibility_criteria', 'Eligibility Criteria'), ('submission_deadlines', 'Submission Deadlines'), ('technical_requirements', 'Technical Requirements'), ('scope_of_work', 'Scope of Work'), ('payment_terms', 'Payment Terms'), ('penalties_and_risks', 'Penalties and Risks'), ('mandatory_documents', 'Mandatory Documents'), ('evaluation_criteria', 'Evaluation Criteria')], db_index=True, max_length=64)),
                ('doc_type', models.CharField(blank=True, help_text='Classified solicitation type (federal_rfq / state_ifb / rfp / …)', max_length=64)),
                ('rating', models.CharField(choices=[('up', 'Thumbs up'), ('down', 'Thumbs down')], db_index=True, max_length=8)),
                ('issue_type', models.CharField(blank=True, choices=[('wrong_value', 'Extracted wrong value'), ('wrong_source', 'Wrong source / citation'), ('missing', 'Value is missing'), ('other', 'Other')], max_length=32)),
                ('extracted_value', models.TextField(blank=True)),
                ('correct_value', models.TextField(blank=True)),
                ('comment', models.TextField(blank=True)),
                ('source_text_context', models.TextField(blank=True)),
                ('used_in_finetune', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FineTuneJob',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('extraction_type', models.CharField(choices=[('executive_overview', 'Executive Overview'), ('eligibility_criteria', 'Eligibility Criteria'), ('submission_deadlines', 'Submission Deadlines'), ('technical_requirements', 'Technical Requirements'), ('scope_of_work', 'Scope of Work'), ('payment_terms', 'Payment Terms'), ('penalties_and_risks', 'Penalties and Risks'), ('mandatory_documents', 'Mandatory Documents'), ('evaluation_criteria', 'Evaluation Criteria')], db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('uploading', 'Uploading dataset'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=16)),
                ('azure_job_id', models.CharField(blank=True, db_index=True, max_length=256)),
                ('azure_file_id', models.CharField(blank=True, max_length=256)),
                ('base_model', models.CharField(blank=True, max_length=128)),
                ('fine_tuned_model_id', models.CharField(blank=True, max_length=256)),
                ('feedback_count', models.PositiveIntegerField(default=0)),
                ('estimated_cost_usd', models.FloatField(default=0.0)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='learnedextractionterm',
            new_name='intelligenc_extract_4e985b_idx',
            old_name='intelligenc_extract_6f2b0d_idx',
        ),
        migrations.AddField(
            model_name='fieldfeedback',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_feedbacks', to='documents.document'),
        ),
        migrations.AddIndex(
            model_name='fieldfeedback',
            index=models.Index(fields=['extraction_type', 'rating', 'used_in_finetune'], name='intelligenc_extract_311ba1_idx'),
        ),
        migrations.AddIndex(
            model_name='fieldfeedback',
            index=models.Index(fields=['document', 'field_key'], name='intelligenc_documen_efc1a4_idx'),
        ),
    ]
