# Generated by Django 5.1.15 on 2026-07-10 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0004_documentchunk_contextual_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractedinsight',
            name='extraction_type',
            field=models.CharField(choices=[('executive_overview', 'Executive Overview'), ('eligibility_criteria', 'Eligibility Criteria'), ('submission_deadlines', 'Submission Deadlines'), ('technical_requirements', 'Technical Requirements'), ('scope_of_work', 'Scope of Work'), ('payment_terms', 'Payment Terms'), ('penalties_and_risks', 'Penalties and Risks'), ('mandatory_documents', 'Mandatory Documents'), ('evaluation_criteria', 'Evaluation Criteria'), ('set_asides', 'Set Asides')], db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='fieldfeedback',
            name='extraction_type',
            field=models.CharField(choices=[('executive_overview', 'Executive Overview'), ('eligibility_criteria', 'Eligibility Criteria'), ('submission_deadlines', 'Submission Deadlines'), ('technical_requirements', 'Technical Requirements'), ('scope_of_work', 'Scope of Work'), ('payment_terms', 'Payment Terms'), ('penalties_and_risks', 'Penalties and Risks'), ('mandatory_documents', 'Mandatory Documents'), ('evaluation_criteria', 'Evaluation Criteria'), ('set_asides', 'Set Asides')], db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='finetunejob',
            name='extraction_type',
            field=models.CharField(choices=[('executive_overview', 'Executive Overview'), ('eligibility_criteria', 'Eligibility Criteria'), ('submission_deadlines', 'Submission Deadlines'), ('technical_requirements', 'Technical Requirements'), ('scope_of_work', 'Scope of Work'), ('payment_terms', 'Payment Terms'), ('penalties_and_risks', 'Penalties and Risks'), ('mandatory_documents', 'Mandatory Documents'), ('evaluation_criteria', 'Evaluation Criteria'), ('set_asides', 'Set Asides')], db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='learnedextractionterm',
            name='extraction_type',
            field=models.CharField(choices=[('executive_overview', 'Executive Overview'), ('eligibility_criteria', 'Eligibility Criteria'), ('submission_deadlines', 'Submission Deadlines'), ('technical_requirements', 'Technical Requirements'), ('scope_of_work', 'Scope of Work'), ('payment_terms', 'Payment Terms'), ('penalties_and_risks', 'Penalties and Risks'), ('mandatory_documents', 'Mandatory Documents'), ('evaluation_criteria', 'Evaluation Criteria'), ('set_asides', 'Set Asides')], db_index=True, max_length=64),
        ),
    ]
