# Generated by Django 5.1.15 on 2026-07-17 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0005_alter_extractedinsight_extraction_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldfeedback',
            name='last_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldfeedback',
            name='recheck_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fieldfeedback',
            name='resolution_status',
            field=models.CharField(choices=[('pending', 'Pending re-check'), ('resolved', 'Resolved'), ('recurred', 'Recurred')], db_index=True, default='pending', max_length=16),
        ),
    ]
