# Generated by Django 5.1.15 on 2026-07-16 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccountmeta',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('team_leader', 'Team Leader'), ('user', 'General User')], db_index=True, default='user', max_length=16),
        ),
    ]
