# Generated by Django 5.1.15 on 2026-07-17 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_useraccountmeta_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccountmeta',
            name='keyword_fields',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
