# Generated by Django 5.1.15 on 2026-05-22 06:08

import django.db.models.deletion
import uuid
from django.db import migrations, models

STAGE_CHOICES = [
    ("uploaded", "Uploaded"),
    ("queued", "Queued"),
    ("intake_processing", "Intake Processing"),
    ("intake_completed", "Intake Completed"),
    ("ocr_processing", "OCR Processing"),
    ("ocr_completed", "OCR Completed"),
    ("sectioning_processing", "Sectioning Processing"),
    ("sectioning_completed", "Sectioning Completed"),
    ("chunking_processing", "Chunking Processing"),
    ("chunking_completed", "Chunking Completed"),
    ("embedding_processing", "Embedding Processing"),
    ("embedding_completed", "Embedding Completed"),
    ("extraction_processing", "Extraction Processing"),
    ("extraction_completed", "Extraction Completed"),
    ("summary_processing", "Summary Processing"),
    ("completed", "Completed"),
    ("failed", "Failed"),
]

LEGACY_STATUS_MAP = {
    "uploaded": "uploaded",
    "queued": "queued",
    "processing": "intake_processing",
    "completed": "completed",
    "failed": "failed",
}


def forwards_copy_status(apps, schema_editor):
    ProcessingJob = apps.get_model("processing", "ProcessingJob")
    for job in ProcessingJob.objects.all():
        legacy = getattr(job, "status", None) or "queued"
        job.current_stage = LEGACY_STATUS_MAP.get(legacy, legacy)
        if job.current_stage == "completed":
            job.completed_stages = ["intake_completed"]
        job.save(update_fields=["current_stage", "completed_stages"])


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_tender_alter_document_status_and_more"),
        ("processing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessingStageLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "stage",
                    models.CharField(choices=STAGE_CHOICES, db_index=True, max_length=64),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("started", "Started"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        max_length=16,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error", models.JSONField(blank=True, default=dict)),
            ],
            options={"ordering": ["started_at"]},
        ),
        migrations.AddField(
            model_name="processingjob",
            name="completed_stages",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Ordered list of stage values successfully completed.",
            ),
        ),
        migrations.AddField(
            model_name="processingjob",
            name="current_stage",
            field=models.CharField(
                choices=STAGE_CHOICES,
                db_index=True,
                default="queued",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="processingjob",
            name="last_error",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Structured error: error_type, stage, recoverable, retry_count, details.",
            ),
        ),
        migrations.RunPython(forwards_copy_status, migrations.RunPython.noop),
        migrations.RemoveIndex(
            model_name="processingjob",
            name="processing__status_677648_idx",
        ),
        migrations.RemoveField(
            model_name="processingjob",
            name="pipeline_stage",
        ),
        migrations.RemoveField(
            model_name="processingjob",
            name="status",
        ),
        migrations.AddIndex(
            model_name="processingjob",
            index=models.Index(
                fields=["current_stage", "-created_at"], name="processing__current_549cfc_idx"
            ),
        ),
        migrations.AddField(
            model_name="processingstagelog",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stage_logs",
                to="processing.processingjob",
            ),
        ),
        migrations.AddIndex(
            model_name="processingstagelog",
            index=models.Index(fields=["job", "stage"], name="processing__job_id_d7c12e_idx"),
        ),
    ]
