# Generated by Django 5.1.15 on 2026-05-22 05:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=512)),
                ('stored_filename', models.CharField(max_length=512)),
                ('file_path', models.CharField(max_length=1024)),
                ('mime_type', models.CharField(blank=True, max_length=128)),
                ('size_bytes', models.BigIntegerField()),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='uploaded', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('checksum_sha256', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='documents_d_status_dead80_idx')],
            },
        ),
    ]
