# Generated by Django 5.1.15 on 2026-05-22 06:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_code', models.CharField(db_index=True, help_text='Business reference, e.g. RFP-2026-0142', max_length=128, unique=True)),
                ('title', models.CharField(max_length=512)),
                ('organization', models.CharField(blank=True, max_length=256)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('closed', 'Closed'), ('archived', 'Archived')], db_index=True, default='active', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('queued', 'Queued'), ('intake_processing', 'Intake Processing'), ('intake_completed', 'Intake Completed'), ('ocr_processing', 'OCR Processing'), ('ocr_completed', 'OCR Completed'), ('sectioning_processing', 'Sectioning Processing'), ('sectioning_completed', 'Sectioning Completed'), ('chunking_processing', 'Chunking Processing'), ('chunking_completed', 'Chunking Completed'), ('embedding_processing', 'Embedding Processing'), ('embedding_completed', 'Embedding Completed'), ('extraction_processing', 'Extraction Processing'), ('extraction_completed', 'Extraction Completed'), ('summary_processing', 'Summary Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='uploaded', max_length=64),
        ),
        migrations.CreateModel(
            name='DocumentExtractedContent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_text', models.TextField(blank=True)),
                ('page_map', models.JSONField(blank=True, default=list, help_text='[{"page": 1, "start_offset": 0, "end_offset": 1200, ...}]')),
                ('layout_structure', models.JSONField(blank=True, default=dict, help_text='Blocks, tables, headers detected during OCR/layout parse.')),
                ('section_hierarchy', models.JSONField(blank=True, default=list, help_text='Nested sections, e.g. [{"title": "Eligibility", "level": 1, "children": []}]')),
                ('content_ready', models.BooleanField(default=False, help_text='True when raw_text and page_map are populated (post-OCR).')),
                ('pipeline_version', models.CharField(default='1.0.0', max_length=32)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_content', to='documents.document')),
            ],
            options={
                'verbose_name_plural': 'document extracted contents',
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_type', models.CharField(choices=[('original', 'Original RFP/RFQ'), ('revision', 'Revised Version'), ('corrigendum', 'Corrigendum'), ('addendum', 'Addendum'), ('clarification', 'Clarification Response'), ('annexure', 'Annexure / Technical Spec'), ('other', 'Other')], db_index=True, default='original', max_length=32)),
                ('version_label', models.CharField(help_text="Display label, e.g. 'Version 2', 'Corrigendum A'", max_length=128)),
                ('version_sequence', models.PositiveIntegerField(default=1, help_text='Monotonic sequence within tender for ordering.')),
                ('is_current', models.BooleanField(db_index=True, default=True, help_text='Active version for retrieval and summarization.')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='version', to='documents.document')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='documents.documentversion')),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_versions', to='documents.tender')),
            ],
            options={
                'ordering': ['tender', 'version_sequence'],
            },
        ),
        migrations.CreateModel(
            name='SourceReference',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_kind', models.CharField(choices=[('extraction', 'Structured Extraction'), ('summary', 'Summary Citation'), ('citation', 'RAG Citation'), ('comparison', 'Version Comparison')], db_index=True, default='citation', max_length=32)),
                ('source_document_label', models.CharField(blank=True, help_text='Human-readable source, e.g. filename or version label.', max_length=512)),
                ('page', models.PositiveIntegerField(blank=True, null=True)),
                ('section', models.CharField(blank=True, max_length=512)),
                ('section_path', models.CharField(blank=True, help_text="Hierarchical path, e.g. 'Volume II > Eligibility Criteria'", max_length=1024)),
                ('chunk_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('char_offset_start', models.PositiveIntegerField(blank=True, null=True)),
                ('char_offset_end', models.PositiveIntegerField(blank=True, null=True)),
                ('confidence', models.DecimalField(blank=True, decimal_places=4, help_text='0.0000–1.0000', max_digits=5, null=True)),
                ('excerpt', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_references', to='documents.document')),
                ('document_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_references', to='documents.documentversion')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['document', 'reference_kind'], name='documents_s_documen_6f831c_idx'), models.Index(fields=['document_version', 'page'], name='documents_s_documen_43357c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='documentversion',
            index=models.Index(fields=['tender', 'is_current'], name='documents_d_tender__185d7b_idx'),
        ),
        migrations.AddIndex(
            model_name='documentversion',
            index=models.Index(fields=['tender', 'version_type'], name='documents_d_tender__282ed9_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentversion',
            constraint=models.UniqueConstraint(fields=('tender', 'version_sequence'), name='unique_tender_version_sequence'),
        ),
    ]
