# Generated by Django 5.1.15 on 2026-05-22 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_tender_alter_document_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('queued', 'Queued'), ('intake_processing', 'Intake Processing'), ('intake_completed', 'Intake Completed'), ('parsing_processing', 'Parsing Processing'), ('parsing_completed', 'Parsing Completed'), ('ocr_processing', 'OCR Processing'), ('ocr_completed', 'OCR Completed'), ('sectioning_processing', 'Sectioning Processing'), ('sectioning_completed', 'Sectioning Completed'), ('chunking_processing', 'Chunking Processing'), ('chunking_completed', 'Chunking Completed'), ('embedding_processing', 'Embedding Processing'), ('embedding_completed', 'Embedding Completed'), ('extraction_processing', 'Extraction Processing'), ('extraction_completed', 'Extraction Completed'), ('summary_processing', 'Summary Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='uploaded', max_length=64),
        ),
    ]
