# Generated by Django 5.1.15 on 2026-07-16 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_document_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='admin_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='document',
            name='admin_note_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
