# Generated by Django 5.1.15 on 2026-07-17 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_document_admin_note_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='marked_done',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='marked_done_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
