# Generated by Django 5.1.15 on 2026-05-22 06:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0003_alter_document_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParsedDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parsing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=32)),
                ('total_pages', models.PositiveIntegerField(default=0)),
                ('raw_text', models.TextField(blank=True)),
                ('structured_text', models.TextField(blank=True, help_text='Normalized reading-order text with section markers.')),
                ('parsing_metadata', models.JSONField(blank=True, default=dict)),
                ('parsing_quality_score', models.FloatField(default=0.0, help_text='Aggregate quality 0.0–1.0 across pages.')),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parsed_document', to='documents.document')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentSection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=512)),
                ('content', models.TextField(blank=True)),
                ('page_start', models.PositiveIntegerField(default=1)),
                ('page_end', models.PositiveIntegerField(default=1)),
                ('section_order', models.PositiveIntegerField(default=0)),
                ('parsed_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='parsing.parseddocument')),
            ],
            options={
                'ordering': ['section_order'],
            },
        ),
        migrations.CreateModel(
            name='DocumentPage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_number', models.PositiveIntegerField()),
                ('extracted_text', models.TextField(blank=True)),
                ('extraction_method', models.CharField(choices=[('native_pdf', 'Native PDF Text'), ('ocr', 'OCR (Tesseract)'), ('docx_native', 'DOCX Native')], default='native_pdf', max_length=32)),
                ('ocr_used', models.BooleanField(default=False)),
                ('quality_score', models.FloatField(default=0.0)),
                ('parsed_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='parsing.parseddocument')),
            ],
            options={
                'ordering': ['page_number'],
                'constraints': [models.UniqueConstraint(fields=('parsed_document', 'page_number'), name='unique_parsed_page_number')],
            },
        ),
    ]
