# Generated by Django 5.1 on 2026-05-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parsing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentsection",
            name="level",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Hierarchy depth (1=top, 2=1.1, etc.).",
            ),
        ),
        migrations.AddField(
            model_name="documentsection",
            name="parent_section_order",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="section_order of parent section, if nested.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="documentsection",
            name="section_path",
            field=models.CharField(
                blank=True,
                help_text='Full path, e.g. "Instructions > 1.1 Submission".',
                max_length=1024,
            ),
        ),
    ]
