# Generated by Django 5.1.15 on 2026-05-22 08:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0003_alter_document_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentChatSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=256)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='documents.document')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentChatMessage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=16)),
                ('content', models.TextField()),
                ('citations', models.JSONField(blank=True, default=list, help_text='Grounded citations: chunk_id, page, section, source_text, score')),
                ('retrieval_chunks', models.JSONField(blank=True, default=list, help_text='Chunks sent to the LLM for this turn')),
                ('token_usage', models.JSONField(blank=True, default=dict)),
                ('model_metadata', models.JSONField(blank=True, default=dict)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.documentchatsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVectorIndex',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_count', models.PositiveIntegerField(default=0)),
                ('embedding_model', models.CharField(max_length=128)),
                ('collection_name', models.CharField(max_length=128)),
                ('indexed_at', models.DateTimeField()),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vector_index', to='documents.document')),
            ],
            options={
                'verbose_name_plural': 'document vector indexes',
            },
        ),
    ]
