# Generated by Django 5.1.15 on 2026-05-25 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentvectorindex',
            name='indexed_chunk_ids',
            field=models.JSONField(blank=True, default=list, help_text='Chroma chunk IDs currently indexed for this document.'),
        ),
    ]
