# Generated by Django 5.1.15 on 2026-07-10 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_documentvectorindex_backend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentvectorindex',
            name='indexed_chunk_ids',
            field=models.JSONField(blank=True, default=list, help_text='Chunk IDs currently indexed for this document.'),
        ),
    ]
